### ISSUE TITLE
Don't use the Net::SSH2 namespace, please

### ISSUE THREAD

**Issue by salva** [lamboley/Net-SSH2-SFTP-Perl#1]
Hi, using the namespace Net::SSH2 for a module that works on top of Net::SSH::Perl is probably going to be very confusing. So, please don't do that.

Also, instead of forking your module from the old, buggy and unmaintained Net::SFTP, you should consider wrtting a backend for Net::SFTP::Foreign.

Cheers

**Comment by lamboley** [comment]
Hi,

Thanks for advices, i will change the namespace, i wouldn't want to trouble users. Which is better : using namespace of Net::SSH::Perl or create my own under Net:: ?

I will also take a look at Net::SFTP::Foreign. Doing something like Net::SFTP::Foreign::Backend::Net_SSH2 but on top of Net::SSH::Perl could be of some interest.

Cheers
